  title: neovim-ide
description: Dockerized NeoVim IDE configuration based on the LazyVim plugin
baseurl: "/neovim-ide"
url: "https://0x07cb.github.io"
lang: en

# Supprimez ces lignes
# languages: ["en", "fr"]
# default_lang: "en"
# exclude_from_localization: ["scripts", "src"]
# parallel_localization: true

# plugins:
#   - jekyll-multiple-languages-plugin