title: neovim-ide
description: Dockerized NeoVim IDE configuration based on the LazyVim plugin
baseurl: "/neovim-ide"
url: "https://0x07cb.github.io"
lang: en

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-seo-tag

github:
  is_project_page: false
