title: neovim-ide
description: Dockerized NeoVim IDE configuration based on the LazyVim plugin
baseurl: "/neovim-ide"
url: "https://0x07cb.github.io"
lang: en

languages:
  en:
    name: English
    lang_code: en
    site_title: neovim-ide
    site_description: Dockerized NeoVim IDE configuration based on the LazyVim plugin
  fr:
    name: Français
    lang_code: fr
    site_title: neovim-ide
    site_description: Configuration de NeoVim dockerisée basée sur le plugin LazyVim

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-seo-tag

github:
  is_project_page: false